alias lst='ls -clhtr'
alias up='sudo apt-get update && sudo apt-get dist-upgrade'
alias mi='mediainfo'
alias htop='htop -C'
alias news='newsbeuter'
alias bcal='gcal -s Mon --cc-holidays=SI .'
alias 2017='gcal --cc-holidays=SI -s Mon -n 2017'
alias search='apt-cache search'
alias nvim='nvim -c "colors molokai"'
alias docx='unoconv -f text --stdout'
