alias lst='ls -clhtr'
alias up='sudo apt-get update && sudo apt-get dist-upgrade'
alias mi='mediainfo'
#alias open='thunar'
alias htop='htop -C'
alias vi='vim'
alias news='newsbeuter'
alias bcal='gcal -s Mon --cc-holidays=SI .'
alias 2017='gcal --cc-holidays=SI -s Mon -n 2017'
alias nvim='nvim -c "colors molokai"'
