#!/bin/bash

set -e
set -x # verbosity

cd ~/source/postbang # < set this to the place where root postbang source git is

git pull

cp -rb .config/* ~/.config/
cp -rb .icons/* ~/.icons/
cp -rb .themes/* ~/.themes/

cp -rb .urxvt/* ~/.urxvt/

cp -rb bin/* ~/bin/

cp -b .bashrc ~
cp -b .bash_aliases ~
cp -b .conkyrc ~
cp -b .conkyrcdwm ~
cp -b .gtkrc-2.0* ~
cp -b .Xresources ~
cp -b .profile ~
cp -b .xsessionrc ~
cp -b .tmux* ~

