#!/bin/bash

set -e

# config
srcdir="$HOME/source/postbang" # < set this to the place where root postbang source git is

# main
if [  ! -d "$srcdir" ]
then
echo "$srcdir not found, exiting." ; exit
else
cd "$srcdir" 
fi

git pull

# the "cp -u" switch will
# copy only when the SOURCE file is newer than the destination file or when the destination file is missing.
# which may or may not be what you want.

cp -vurb .config/* ~/.config/
cp -vurb .icons/* ~/.icons/
cp -vurb .themes/* ~/.themes/

cp -vurb .urxvt/* ~/.urxvt/

cp -vurb bin/* ~/bin/

cp -vub .bashrc ~
cp -vub .bash_aliases ~
cp -vub .conkyrc ~
cp -vub .conkyrcdwm ~
cp -vub .gtkrc-2.0* ~
cp -vub .Xresources ~
cp -vub .profile ~
cp -vub .xsessionrc ~
cp -vub .tmux* ~
cp -vub .wbar ~

# sudo here
# set +x # verbosity off

echo
echo "65% stupid, run at your own risk from now on"

sudo cp -vurb usr/* /usr/ 
